
---
- hosts: apt-hosts
  #remote_user: root
  become: yes
  #become_user: root

  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      #update_cache=yes       :Run the equivalent of apt-get update command on all servers
      #force_apt_get=yes      :Do not use the aptitude command, use the apt-get command
      #cache_valid_time=3600  :Update the apt cache if its older than the cache_valid_time

    - name: dist upgrade force
      apt: upgrade=dist force_apt_get=yes

